services:
  gunicorn_project:
    build: ./flasktut

  nginx:
    image: docker.io/andylytical/nginx-as-gunicorn-proxy
    pull_policy: always
    ports:
      - "8080:80"
    depends_on:
      - gunicorn_project
