services:
  gunicorn_project:
    image: docker.io/andylytical/flasktut-gunicorn
    pull_policy: always
    # restart: always

  nginx:
    image: docker.io/andylytical/nginx-as-gunicorn-proxy
    pull_policy: always
    ports:
      - "8080:80"
    depends_on:
      - gunicorn_project
